Add admin controls for removing archives and sending email to users
beakerbrowser/hypercloud-ui-hashbase pull request #34
Opened 2017-06-06 22:57 UTC by taravancil

2017-06-07 04:54 UTC, pfrazee requested changes

2017-06-07 04:54 UTC, pfrazee commented on assets/html/archive.html
> +      <% if (isOwner || sessionUser.scopes.includes('admin:dats')) { %>
This doesn't work, unfortunately. The /v1/archives/remove route operates on the session user.

We should use a separate link entirely, that indicates it's an admin action, and we should add a route to the admin API in hypercloud which removes the archive.

2017-06-07 04:57 UTC, pfrazee commented
Need to update the remove-archive bit (or maybe just remove it and do in a separate PR). Email form looks good though!

2017-06-07 04:59 UTC, taravancil commented
Will open a separate PR for the remove archive stuff

2017-06-08 18:39 UTC, taravancil commented
Making this PR directly to beakerbrowser/hashbase. Closing.

2017-06-08 18:39 UTC, closed without merging